repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: detect-private-key
      - id: fix-encoding-pragma
      - id: check-merge-conflict
      - id: check-added-large-files
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint-fix
      - id: markdownlint
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.24.1
    hooks:
      - id: check-github-workflows
      - name: Validate docker-compose.yml
        id: check-jsonschema
        # match docker-compose.yml or docker-compose.yaml
        files: docker-compose\.ya?ml$
        # "https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json"
        args: ["--schemafile", "./.schemas/compose-spec.json"]
      - name: Validate prometheus.yml
        id: check-jsonschema
        files: services-monitoring/prometheus/prometheus\.yml$
        # https://json.schemastore.org/prometheus.json
        args: ["--schemafile", "./.schemas/prometheus.json"]
      - name: Validate traefik.yml
        id: check-jsonschema
        files: system/traefik\.yml$
        # https://json.schemastore.org/traefik-v2.json
        args: ["--schemafile", "./.schemas/traefik-v2.json"]
