version: "3.7"
services:
  task_creator:
    image: hskrk/telegram_phabricator:latest
    secrets:
      - telegram_token
      - phabricator_token
    command:
      - /bin/sh
      - -c
      - export TELEGRAM_TOKEN=$$(cat /run/secrets/telegram_token) && export PHABRICATOR_TOKEN=$$(cat /run/secrets/phabricator_token) && python3 main.py
    environment:
      - PHABRICATOR_URL=${PHABRICATOR_URL}
      - PHABRICATOR_URL_API=${PHABRICATOR_URL_API}
      - TELEGRAM_CHAT_NAME=${TELEGRAM_CHAT_NAME}
    restart: unless-stopped

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  tele_notifier:
    image: ghcr.io/hbrylkowski/phabricatortelenotifier:master
    restart: unless-stopped

secrets:
  telegram_token:
    external: true
  phabricator_token:
    external: true
  phabricator-tele-notifier.yaml:
    external: true
