version: "3.7"
services:
  task_creator:
    image: hskrk/telegram_phabricator:latest
    secrets:
      - telegram_token
      - phabricator_token
    command:
      - /bin/sh
      - -c
      - export TELEGRAM_TOKEN=$$(cat /run/secrets/telegram_token) && export PHABRICATOR_TOKEN=$$(cat /run/secrets/phabricator_token) && python3 main.py
    environment:
      - PHABRICATOR_URL=${PHABRICATOR_URL}
      - PHABRICATOR_URL_API=${PHABRICATOR_URL_API}
      - TELEGRAM_CHAT_NAME=${TELEGRAM_CHAT_NAME}
    restart: unless-stopped
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 5

  tele_notifier:
    image: ghcr.io/hackerspacekrk/phabricatortelenotifier:latest
    restart: unless-stopped
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=system_default"
        - "traefik.http.services.tele_notifier.loadbalancer.server.port=8080"
        - "traefik.http.routers.tele_notifier.rule=Host(`telenotifier.apps.hskrk.pl`)  && ClientIP(`10.0.0.0/8`)"
        - "traefik.http.routers.tele_notifier.tls=true"
        - "traefik.http.routers.tele_notifier.tls.certresolver=myresolver"
    networks:
      - system_default
    secrets:
      - source: phabricator-tele-notifier.yaml
        target: /run/secrets/config.yaml

secrets:
  telegram_token:
    external: true
  phabricator_token:
    external: true
  phabricator-tele-notifier.yaml:
    external: true

configs:
  phabricator-tele-notifier.yaml:
    external: true
networks:
  system_default:
    external: true
