server:
    disable: true
  
positions:
    filename: /tmp/positions.yaml
  
clients:
    - url: http://loki:3100/loki/api/v1/push
      tenant_id: docker

scrape_configs:
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:1514
      listen_protocol: tcp
      idle_timeout: 60s
      label_structured_data: yes
      labels:
        job: "syslog"
    relabel_configs:
      - source_labels: [ '__syslog_message_hostname' ]
        target_label: 'host'
      - source_labels: [ "__syslog_message_app_name" ]
        target_label: "appname"
      - source_labels: ["__syslog_message_severity"]
        target_label: "severity"
      - source_labels: ["__syslog_message_facility"]
        target_label: "facility"