http:
  services:
    oscilloscope-service:
      loadBalancer:
        servers:
          - url: "http://10.12.10.145"
    spectrum-analyzer-service:
      loadBalancer:
        servers:
          - url: "http://10.12.10.144"

  routers:
    oscilloscope-router:
      entryPoints:
        - "web"
        - "websecure"
      service: oscilloscope-service
      rule: "Host(`oscyloskop.at.hskrk.pl`) || Host(`oscilloscope.at.hskrk.pl`)"
      tls:
        certResolver: myresolver
      middlewares:
        - authentik@docker
    spectrum-analyzer-router:
      entryPoints:
        - "web"
        - "websecure"
      service: spectrum-analyzer-service
      rule: "Host(`sa.at.hskrk.pl`)"
      tls:
        certResolver: myresolver
      middlewares:
        - authentik@docker
