http:
  services:
    oscilloscope-service:
      loadBalancer:
        servers:
          - url: "http://10.12.10.145"
    spectrum-analyzer-service:
      loadBalancer:
        servers:
          - url: "http://10.12.10.144"
    spectrum-analyzer-wss-service:
      loadBalancer:
        servers:
          - url: "http://10.12.10.144:5900"

  routers:
    oscilloscope-router:
      entryPoints:
        - "web"
        - "websecure"
      service: oscilloscope-service
      rule: "Host(`oscyloskop.at.hskrk.pl`) || Host(`oscilloscope.at.hskrk.pl`)"
      tls:
        certResolver: myresolver
      middlewares:
        - authentik@docker
    spectrum-analyzer-router:
      entryPoints:
        - "web"
        - "websecure"
      service: spectrum-analyzer-service
      rule: "Host(`sa.at.hskrk.pl`)"
      tls:
        certResolver: myresolver
      middlewares:
        - authentik@docker
    spectrum-analyzer-wss-router:
      entryPoints:
        - "sa-wss"
      service: spectrum-analyzer-wss-service
      rule: "Host(`sa.at.hskrk.pl`) && Port(`5900`)"
      tls:
        certResolver: myresolver
      middlewares:
        - authentik@docker
