go2rtc:
  webrtc:
    candidates:
      - frigate.apps.hskrk.pl:8555
      - 45.66.23.243:8555
      - stun:8555
  streams:
    lab_elektroniczny: rtsp://{FRIGATE_ELAB_RTSP}
    softroom: rtsp://{FRIGATE_SOFTROOM_RTSP}
    hardroom_od_drzwi: rtsp://{FRIGATE_HARDROOM_OD_DRZWI_RTSP}
    hardroom_na_drzwi: rtsp://{FRIGATE_HARDROOM_NA_DRZWI_RTSP}
    korytarz: ffmpeg:rtsp://{FRIGATE_KORYTARZ_RTSP}#video=h264#rotate=90
    korytarz_wyjscie: ffmpeg:rtsp://{FRIGATE_KORYTARZ_WYJSCIE_RTSP}#video=h264#rotate=90
    magazynek_od_drzwi: rtsp://{FRIGATE_MAGAZYNEK_OD_DRZWI_RTSP}
    magazynek_na_drzwi: ffmpeg:http://{FRIGATE_MAGAZYNEK_NA_DRZWI_HTTP}#video=h264

cameras:
  lab_elektroniczny:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/lab_elektroniczny
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
  softroom:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/softroom
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
  hardroom_od_drzwi:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/hardroom_od_drzwi
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
  hardroom_na_drzwi:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/hardroom_na_drzwi
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
  korytarz:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/korytarz
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
  korytarz_wyjscie:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/korytarz_wyjscie
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
            - rtmp
  magazynek_od_drzwi:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/magazynek_od_drzwi
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
  magazynek_na_drzwi:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/magazynek_na_drzwi
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record

mqtt:
  enabled: False

telemetry:
  version_check: False

detectors:
  cpu1:
    type: cpu
    num_threads: 16

detect:
  fps: 2

snapshots:
  enabled: True

record:
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 1
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 10
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: motion
      # Optional: Per object retention days
      objects:
        person: 15
