api:
  insecure: true

providers:
  docker:
    exposedByDefault: false
    swarmMode: true
  file:
    directory: "/traefik_files"

entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      trustedIPs:
        - "10.0.0.0/16"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"

  websecure:
    address: ":443"

  sa-wss:
    address: ":5900"

certificatesResolvers:
  myresolver:
    acme:
      storage: "/traefik/acme/acme.json"
      httpChallenge:
        entryPoint: "web"
