version: '3.8'
services:
  phorge:
    image: ghcr.io/hackerspacekrk/phorge-docker:latest
    depends_on:
      - phorge-mysql
    environment:
      - MYSQL_HOST=phorge-mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD_FILE=/run/secrets/phorge_mysql_password
      - BASE_URI=phorge.apps.hskrk.pl
      - MAILERS_CONFIG_FILE=/tmp/phorge-mailers.json
      - PROTOCOL=https
      - MINIO_SERVER=minio
      - MINIO_PORT=9000
      - MINIO_BUCKET=phorge
      - MINIO_SERVER_ACCESS_KEY_FILE=/run/secrets/phorge_minio_access_key
      - MINIO_SERVER_SECRET_KEY_FILE=/run/secrets/phorge_minio_secret_key
    volumes:
      - ph-repo:/var/repo
    secrets:
      - phorge_mysql_password
      - source: phorge_mailers_config
        target: /tmp/phorge-mailers.json
      - phorge_minio_access_key
      - phorge_minio_secret_key
    healthcheck:
      test: ["CMD", "curl", "-H", "Host: phorge.apps.hskrk.pl", "http://localhost:80/status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - system_default
      - phorge_default
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=system_default"
        - "traefik.http.services.phorge.loadbalancer.server.port=80"
        - "traefik.http.routers.phorge.rule=Host(`phorge.apps.hskrk.pl`)"
        - "traefik.http.routers.phorge.tls=true"
        - "traefik.http.routers.phorge.tls.certresolver=myresolver"
  phorge-mysql:
    image: mariadb:10.6.14
    volumes:
      - phorge-database-volume:/var/lib/mysql
    configs:
      - source: mysql_config
        target: /etc/mysql/conf.d/mysql-config.cnf
    secrets:
      - phorge_mysql_password
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/phorge_mysql_password
    networks:
      - phorge_default
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
secrets:
  phorge_mysql_password:
    external: true
  phorge_mailers_config:
    external: true
  phorge_minio_access_key:
    external: true
  phorge_minio_secret_key:
    external: true
configs:
  mysql_config:
    file: ./mysql-config.cnf
volumes:
  phorge-database-volume:
  ph-repo:
networks:
  system_default:
    external: true
  phorge_default:
    external: false
  minio:
    external: true
    name: minio
