version: '3.8'
services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    volumes:
      - netbootxyz-config:/config
      - netbootxyz-assets:/assets
    ports:
      - 69:69/udp # TFTP
      # ephemeral range
      - 33000-33200:33000-33200/udp # iPXE
    environment:
      - ENV_TFTPD_OPTS="-R 33000:33200"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=system_default"
        - "traefik.http.services.netbootxyz.loadbalancer.server.port=3000"
        - "traefik.http.routers.netbootxyz.rule=Host(`netbootxyz.apps.hskrk.pl`)"
        - "traefik.http.routers.netbootxyz.middlewares=authentik@docker"
        - "traefik.http.routers.netbootxyz.tls=true"
        - "traefik.http.routers.netbootxyz.tls.certresolver=myresolver"
    networks:
      - system_default
volumes:
  netbootxyz-config:
  netbootxyz-assets:
networks:
  system_default:
    external: true
