version: "3.7"
services:
  db:
    image: postgres:15.4
    restart: unless-stopped
    networks:
      - spejstore
    volumes:
      - spejstore-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} #TODO CHANGE
    healthcheck:
      #CHANGE 1: this command checks if the database is ready, right on the source db server
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 5
  labelmaker:
    image: ghcr.io/hackerspacekrk/spejstore-labelmaker:master
    restart: unless-stopped
    environment:
      - LABELMAKER_LABEL_SIZE=[80,40]
      - LABELMAKER_IPP_PRINTER_URL=ipp://10.12.10.123:631/printers/Zebra_TLP2844
      - LABELMAKER_CODE_PREFIX="https://spejstore.apps.hskrk.pl/"
    networks:
      - spejstore
      - system_default
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=system_default"
        - "traefik.http.services.spejstore-labelmaker.loadbalancer.server.port=4567"
        - "traefik.http.routers.spejstore-labelmaker.rule=Host(`spejstore-labelmaker.apps.hskrk.pl`)  && ClientIP(`10.0.0.0/8`)"
        - "traefik.http.routers.spejstore-labelmaker.tls=true"
        - "traefik.http.routers.spejstore-labelmaker.tls.certresolver=myresolver"
  web:
    restart: unless-stopped
    command: bash -c "python manage.py collectstatic --no-input --clear && python manage.py migrate && gunicorn --workers 1 --threads 4 -b 0.0.0.0:8000 --capture-output --error-logfile - --access-logfile - spejstore.wsgi:application"
    image: ghcr.io/hackerspacekrk/spejstore:master
    networks:
      - system_default
      - spejstore
      - minio
    secrets:
      - spejstore_clientid
      - spejstore_secret
      - spejstore_s3_access_key
      - spejstore_s3_secret_key
    environment:
      SPEJSTORE_HOST: "https://spejstore.apps.hskrk.pl"
      SPEJSTORE_CLIENT_ID: ${SPEJSTORE_CLIENT_ID}
      SPEJSTORE_SECRET: ${SPEJSTORE_SECRET}
      SPEJSTORE_DB_NAME: ${POSTGRES_DB}
      SPEJSTORE_DB_PASSWORD: ${POSTGRES_PASSWORD}
      SPEJSTORE_DB_USER: ${POSTGRES_USER}
      SPEJSTORE_DB_HOST: ${POSTGRES_HOST}
      SPEJSTORE_ALLOWED_HOSTS: ${SPEJSTORE_ALLOWED_HOSTS}
      SPEJSTORE_ENV: ${SPEJSTORE_ENV}
      SPEJSTORE_FILE_STORAGE_TYPE: ${SPEJSTORE_FILE_STORAGE_TYPE}
      SPEJSTORE_LABEL_API: http://labelmaker:4567/
      # S3 bucket
      SPEJSTORE_S3_ACCESS_KEY: ${SPEJSTORE_S3_ACCESS_KEY}
      SPEJSTORE_S3_SECRET_KEY: ${SPEJSTORE_S3_SECRET_KEY}
      SPEJSTORE_S3_ENDPOINT_URL: ${SPEJSTORE_S3_ENDPOINT_URL}
      SPEJSTORE_S3_DOMAIN_NAME: ${SPEJSTORE_S3_DOMAIN_NAME}
      SPEJSTORE_S3_BUCKET_NAME: ${SPEJSTORE_S3_BUCKET_NAME}
      SPEJSTORE_S3_MEDIA_LOCATION: ${SPEJSTORE_S3_MEDIA_LOCATION}
    depends_on:
      - db
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=system_default"
        - "traefik.http.services.spejstore.loadbalancer.server.port=8000"
        - "traefik.http.routers.spejstore.rule=Host(`spejstore.apps.hskrk.pl`)"
        - "traefik.http.routers.spejstore.tls=true"
        - "traefik.http.routers.spejstore.tls.certresolver=myresolver"

volumes:
  spejstore-db:
  build_static:

secrets:
  spejstore_secret:
    external: true
  spejstore_clientid:
    external: true
  spejstore_s3_access_key:
    external: true
  spejstore_s3_secret_key:
    external: true

networks:
  system_default:
    external: true
  spejstore:
    internal: true
    external: false
  minio:
    external: true
    name: minio
