version: "3.7"
services:
  db:
    image: ghcr.io/hackerspacekrk/spejstore/postgres-hstore:latest
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - spejstore-pg:/var/lib/postgresql/data
    networks:
      - spejstore
  web:
    image: ghcr.io/hackerspacekrk/spejstore:latest
    restart: always
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    networks:
      - system_default
      - spejstore
    secrets:
      - spejstore_clientid
      - spejstore_secret
    environment:
      SPEJSTORE_CLIENT_ID: ${SPEJSTORE_CLIENTID}
      SPEJSTORE_SECRET: ${SPEJSTORE_SECRET}
    depends_on:
      - db
    env_file:
      - spejstore.env
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=system_default"
        - "traefik.http.services.spejstore.loadbalancer.server.port=8000"
        - "traefik.http.routers.spejstore.rule=Host(`spejstore.apps.hskrk.pl`)"
        - "traefik.http.routers.spejstore.tls=true"
        - "traefik.http.routers.spejstore.tls.certresolver=myresolver"

volumes:
  spejstore-pg:

secrets:
  spejstore_secret:
    external: true
  spejstore_clientid:
    external: true

networks:
  system_default:
    external: true
  spejstore:
