version: "3.8"

services:
  minio:
    networks:
      - minio
      - system_default
    image: quay.io/minio/minio:RELEASE.2023-08-16T20-17-30Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio:/data
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=system_default"
        - "traefik.http.services.minio.loadbalancer.server.port=9001"
        - "traefik.http.routers.minio.rule=Host(`minio.apps.hskrk.pl`)"
        - "traefik.http.routers.minio.tls=true"
        - "traefik.http.routers.minio.tls.certresolver=myresolver"

volumes:
  minio:

networks:
  minio:
    attachable: true
    name: minio
  system_default:
    external: true